#cloud-config
hostname: "${hostname}"
fqdn: "${hostname}.localdomain"
manage_etc_hosts: false

# Write the disk setup script
write_files:
  - path: /var/lib/cloud/scripts/per-instance/setup-disks.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      LOG_FILE="/var/log/setup-disks.log"
      exec > >(tee -a $LOG_FILE) 2>&1  # Redirect stdout and stderr to log file

      echo "Starting dynamic disk setup..." >> $LOG_FILE

      # Loop over the expected disk names (assuming nvme devices)
      for disk_number in {1..10}; do
        device="/dev/nvme$${disk_number}n1"
        mount_point="/data$${disk_number}"

        # Check if the device exists
        if [ -b "$device" ]; then
          echo "Found device $device" >> $LOG_FILE

          # Check if the disk is already formatted
          if ! blkid "$device"; then
            echo "Formatting $device as XFS" >> $LOG_FILE
            mkfs.xfs "$device"
          fi

          # Create mount point and mount the disk
          mkdir -p "$mount_point"
          echo "Mounting $device at $mount_point" >> $LOG_FILE
          mount "$device" "$mount_point"
          chown gpadmin:gpadmin "$mount_point"
          chmod 700 "$mount_point"
        else
          echo "Device $device not found, skipping" >> $LOG_FILE
        fi
      done

# Execute the disk setup script
runcmd:
  - /var/lib/cloud/scripts/per-instance/setup-disks.sh
